# Generated by Django 6.0.5 on 2026-05-13 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available_cash', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('invested_cash', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('total_pnl', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('limit_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('executed_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('stoploss', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.portfolio')),
            ],
        ),
    ]
