# Generated by Django 6.0.5 on 2026-05-14 01:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='description', max_length=20000),
        ),
        migrations.AlterField(
            model_name='order',
            name='limit_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15)),
                ('average_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=15)),
                ('target', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('stoploss', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='dashboard.portfolio')),
            ],
        ),
    ]
