# Generated by Django 6.0.5 on 2026-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_portfolio_description_alter_order_limit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
