# Generated by Django 6.0.5 on 2026-05-15 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_limit_price_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='unrealized_pnl',
        ),
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='dashboard.order'),
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('exit_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=5, max_digits=15)),
                ('target', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('stoploss', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('exit_reason', models.CharField(choices=[('STOPLOSS', 'Stoploss'), ('TARGET', 'Target'), ('MANUAL', 'Manual')], max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.order')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='dashboard.portfolio')),
            ],
        ),
    ]
