# Generated by Django 6.0.5 on 2026-05-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_position_current_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='average_price',
            new_name='entry_price',
        ),
    ]
