# Generated by Django 6.0.5 on 2026-05-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_apitoken'),
        ('dashboard', '0005_rename_average_price_position_entry_price'),
    ]

    operations = [
    ]
